name: k6 Load Test

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  k6-load-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install k6 (stable via Grafana)
      run: |
        sudo apt update
        sudo apt install -y gnupg curl ca-certificates
        curl -fsSL https://dl.k6.io/key.gpg | sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/k6.gpg
        echo "deb https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
        sudo apt update
        sudo apt install k6

    - name: Run all k6 tests
      run: |
        mkdir -p summary
        for file in ./k6/Automation_Practice/*.js; do
          echo "Running $file"
          filename=$(basename "$file" .js)
          k6 run "$file" --summary-export=summary/${filename}.json
        done

    - name: Upload all k6 reports
      uses: actions/upload-artifact@v4
      with:
        name: k6-summaries
        path: summary/
