name: Locust Load Test

on:
  workflow_dispatch: 

jobs:
  locust:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Locust
        run: pip install locust

      - name: Run Locust Test in Headless Mode
        run: |
          locust -f ./locust/locustLMS_EVS.py \
            --headless \
            -u 10 \
            -r 2 \
            --run-time 1m \
            --host=https://automationpractice.com \
            --logfile locust.log \
            --only-summary
          
      - name: Upload Locust Log
        uses: actions/upload-artifact@v4
        with:
          name: locust-log
          path: locust.log
